### PR TITLE
Cell Identification and Classification - Segmentation Plots

### PR DESCRIPTION
**Pull request by srivarra**
**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**
Addresses 5.1 of #10.

Adds plots which show user defined membrane markers as well as a nuclear and membrane overlay.

FOVs used:

- Segmentation Overlay Plots:
  - TONIC_TMA3_R2C5
  - TONIC_TMA4_R10C4
  - TONIC_TMA5_R3C4
  - TONIC_TMA8_R1C2
  - TONIC_TMA9_R4C4
  - TONIC_TMA12_R4C1
  - TONIC_TMA12_R7C6
  - TONIC_TMA18_R4C5
  - TONIC_TMA21_R2C1
  - TONIC_TMA21_R9C1
  - TONIC_TMA23_R1C3
  - TONIC_TMA24_R2C6
- Membrane Markers and Segmentation / Overlay Plot:
  - TONIC_TMA3_R5C2
  - TONIC_TMA3_R11C2
  - TONIC_TMA10_R3C3
  - TONIC_TMA11_R1C6
  - TONIC_TMA13_R1C5
  - TONIC_TMA16_R12C1
  - TONIC_TMA23_R10C2
  - TONIC_TMA24_R10C2

**How did you implement your changes**

- Added the following classes to make plots:
  - `SegmentationOverlayPlot`: Plots the segmentation mask (eroded) alongside the overlay image
  - `MembraneMarkersSegmentationPlot`: Plots the user supplied markers, the sum of those markers, (quantile range 0.05, 0.95) the segmentation mask (eroded) alongside the overlay image.

- Added some utilities:
  - `QuantileNormalization` normalizes the image from a range of (lower_quantile, upper_quantile). Has options to clip the data as well.
 
  - `remove_ticks` removes ticks and tick labels from a given figure or axes, with a specific target axis (x, y, or both)

**Remaining issues**

N/A

Figures are saved in:

*`TONIC_Cohort/supplementary_figs/segmentation_chans_overlays`*

### CODE REVIEW

**Comment by ngreenwald** [comment]
Not sure what the underlying issue is, but the segmentation masks look messed up in illustrator: 
image

**Comment by srivarra** [comment]
@ngreenwald

When saving the grayscale segmentation image, it was saved as raw pixels (not interpolated). Different editor programs load images embedded in pdfs differently. One thing to try was using interpolation, which fixed the issue, however significantly dropped the resolution. Increasing the DPI brought the original issue back. When saved as an `svg` the images behave properly. They are updated to be `svg` now. In addition illustrator opens them up with all the layers (text layers, image layers, image boarder) so it should be easier to manipulate them.

image

**Review by ngreenwald — CHANGES_REQUESTED** [review]
Looks good, will you switch the colors for membrane and nuclear signal and regenerate the images? More typical to use blue for nuclei.

**Comment by srivarra** [comment]
@ngreenwald Swapped the colors, they're updated on the NAS.

**Review by ngreenwald — APPROVED** [review]
Looks good, thanks

**Pull request merged**
