### PR TITLE
Add functional marker visualization process

### LINKED ISSUE #18: Add functional marker thresholding
**Is your feature request related to a problem? Please describe.**

Addresses second-to-last bullet point in #10. Adds a definition for `visualize_marker_thresholds`, a function to visualize various distributions of markers per cell population type with their corresponding threshold.

**Describe the solution you'd like**

Implementation is largely borrowed from `ark.phenotyping.post_cluster_utils.plot_hist_thresholds`. However, this function currently does not handle the case where multiple markers with different thresholds must be specified, so a few changes need to be made:

1. The `marker` and `threshold` parameter should be condensed into a `marker_threshold_info` `dict` param which maps each marker to their corresponding threshold. The user can then specify multiple markers and each marker can have its corresponding threshold visualized.
    1. (INPUT NEEDED) Can we safely assume that all markers have a corresponding `threshold`? `plot_hist_threshold` has support for `threshold=None`, which turns off drawing the vertical threshold line, but if this assumption can be made, `visualize_marker_thresholds` doesn't need to support `None` values for thresholding.
2. The figure dimensions will need to change. Because `plot_hist_threshold` is currently designed to only visualize one marker distribution per population at a time, only one column was needed. There will now need to be `len(marker_threshold_info)` columns in this figure, with column `i` corresponding to the marker at index `i` in `marker_threshold_info.keys()`.
    1. (INPUT NEEDED) if `marker_threshold_info` is significantly large, the figure can blow up. An alternative is to save separate figures for each marker within the same function. Any other suggestions appreciated.
3. An additional loop over each `marker` will need to enclose the current loop over `populations`.
4. The `threshold` is no longer constant, so it should be accessed via `marker_threshold_info[marker]`.

**Additional context**

@ngreenwald where do we want to display the screenshot(s) for showing how Mantis is used to identify these thresholds?

### PR DESCRIPTION
**Pull request by alex-l-kong**
**What is the purpose of this PR?**

Closes #18.

**How did you implement your changes**

Inspiration largely taken from `post_cluster_utils` in `ark`. However, support is added to visualize the distribution of a marker against all cell populations.

### CODE REVIEW

**Review by srivarra — APPROVED** [review]
Looks good!

**Review by camisowers — APPROVED** [review]

**Review by ngreenwald — CHANGES_REQUESTED** [review]
Looks good. Under the function, will you add a couple function calls for the first few plots? See what plot settings you like to make it look nice. 

Cell cluster column = cell_cluster for all
CD45RO: CD4T, Fibroblast
CD38: Endothelium, Cancer_EMT
PDL1: Cancer, Stroma

**Review by ngreenwald — CHANGES_REQUESTED** [review]
Looks good, just a merge conflict

**Review by ngreenwald — CHANGES_REQUESTED** [review]
Merge conflicts

**Comment by alex-l-kong** [comment]
> Merge conflicts

All resolved now, seems to have been caused by the acquisition order PR.

**Review by ngreenwald — APPROVED** [review]

**Pull request merged**
